# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_events', '0002_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
